// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbcY3IbLISczvBZEOAfdn41itTPHJpN9g',
    appId: '1:1042982695076:web:f269ebee451204a79bb631',
    messagingSenderId: '1042982695076',
    projectId: 'fir-flutter-e702b',
    authDomain: 'fir-flutter-e702b.firebaseapp.com',
    storageBucket: 'fir-flutter-e702b.firebasestorage.app',
    measurementId: 'G-CKG2VPWZDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwweWkoArsbX4-Giqx5p471f-Z8oaasNM',
    appId: '1:1042982695076:android:2c79524951bdd6cd9bb631',
    messagingSenderId: '1042982695076',
    projectId: 'fir-flutter-e702b',
    storageBucket: 'fir-flutter-e702b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW7i1QbBhHW4Awdqf3N3M7Yr9mBypXuIQ',
    appId: '1:1042982695076:ios:5757291995e9beba9bb631',
    messagingSenderId: '1042982695076',
    projectId: 'fir-flutter-e702b',
    storageBucket: 'fir-flutter-e702b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW7i1QbBhHW4Awdqf3N3M7Yr9mBypXuIQ',
    appId: '1:1042982695076:ios:5757291995e9beba9bb631',
    messagingSenderId: '1042982695076',
    projectId: 'fir-flutter-e702b',
    storageBucket: 'fir-flutter-e702b.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbcY3IbLISczvBZEOAfdn41itTPHJpN9g',
    appId: '1:1042982695076:web:f8ff6cb5f27e355d9bb631',
    messagingSenderId: '1042982695076',
    projectId: 'fir-flutter-e702b',
    authDomain: 'fir-flutter-e702b.firebaseapp.com',
    storageBucket: 'fir-flutter-e702b.firebasestorage.app',
    measurementId: 'G-1PXD5ZRHXV',
  );
}
